<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'errno' => '/errno.php',
                'iraguadminaddcampus' => '/04-iragu-admin-add-campus.php',
                'iraguadminaddcourt' => '/05-iragu-admin-court-add.php',
                'iraguadmincourtbooking' => '/08-iragu-admin-court-booking.php',
                'iraguadmincustomerrecharge' => '/03-iragu-admin-recharge.php',
                'iraguadminopenbookings' => '/06-iragu-admin-bookings-open.php',
                'iraguadminrechargeoffer' => '/02-iragu-admin-offer-recharge.php',
                'iraguadminregister' => '/00-iragu-admin-register-customer.php',
                'iragucheckavailability' => '/07-iragu-check-availability.php',
                'iragumakeregisteroffer' => '/make-register-offer.php',
                'iragumenuadmin' => '/12-iragu-admin-menu.php',
                'iragumenuuser' => '/13-iragu-user-menu.php',
                'iragupagetemplate' => '/09-iragu-template.php',
                'iragurazorpay' => '/IraguRazorpay.php',
                'iraguuserrecharge' => '/20-iragu-user-recharge.php',
                'iraguuserrechargerazorpay' => '/15-iragu-user-recharge-razorpay.php',
                'iraguwebapp' => '/iragu-webapp.php',
                'loginpage' => '/index.php',
                'pagerazorpaylanding' => '/PageRazorpayLanding.php',
                'pagesignup' => '/PageSignup.php',
                'tablebalance' => '/TableBalance.php',
                'tablepassbook' => '/TablePassbook.php',
                'tablerazorpaypayment' => '/TableRazorpayPayment.php',
                'tablerazorpaysession' => '/TableRazorpaySession.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
